on:

  workflow_call:

  push:

  workflow_dispatch:


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step xy
        id: hello
        uses: yecid-rodriguez-mojix-com/redischeck@master
        with:
          who-to-greet: 'Master Dev'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
